#!/bin/bash
flatpak install com.spotify.Client
flatpak install de.haeckerfelix.Shortwave
flatpak install dev.geopjr.Calligraphy
flatpak install im.riot.Riot
flatpak install io.github.amit9838.mousam
flatpak install io.github.dvlv.boxbuddyrs
flatpak install io.github.seadve.Kooha
flatpak install io.missioncenter.MissionCenter
flatpak install org.gnome.baobab
flatpak install org.gnome.DejaDup
flatpak install org.gnome.gitlab.somas.Apostrophe
flatpak install org.gnome.Podcasts
flatpak install org.libretro.RetroArch
flatpak install org.signal.Signal
flatpak install org.squidowl.halloy
flatpak install org.kde.krita
flatpak install org.kde.kdenlive
flatpak install org.videolan.VLC
flatpak install io.mpv.Mpv
flatpak install com.obsproject.Studio
